import React from 'react';
import { Info } from 'lucide-react';

const Disclaimer = () => (
  <div className="disclaimer">
    <Info size={15} className="disclaimer-icon" color="var(--text-4)" />
    <p className="disclaimer-text">
      <strong>Educational Use Only.</strong> This prediction is generated by a machine learning model
      for educational purposes and is <em>not</em> a substitute for professional medical advice,
      diagnosis, or treatment. Always consult a qualified healthcare professional.
    </p>
  </div>
);

export default Disclaimer;
